// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

//var policyName = "_policy1";

// Configure app
var builder = WebApplication.CreateBuilder(args);

//builder.Services.AddCors(options =>
//{
//    options.AddPolicy(name: policyName,
//                      builder =>
//                      {
//                          builder
//                            //.WithOrigins("http://localhost:8196")
//                            .AllowAnyOrigin()
//                            .AllowAnyMethod()
//                            .AllowAnyHeader();
//                      });
//});

builder.Services.AddCors();

builder.Services.AddPredictionEnginePool<AuditModel1.ModelInput, AuditModel1.ModelOutput>()
    .FromFile("AuditModel1.zip");
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

//app.UseCors(policyName);

app.UseCors((context) =>
{
    context
    .WithOrigins("null")
    //.WithOrigins("http://localhost:8196")
    //.AllowAnyOrigin()
    .AllowAnyMethod()
    .AllowAnyHeader();
});

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<AuditModel1.ModelInput, AuditModel1.ModelOutput> predictionEnginePool, AuditModel1.ModelInput input) =>
        await Task.FromResult(predictionEnginePool.Predict(input)));

// Run app
app.Run();
