
// This file was auto-generated by ML.NET Model Builder. 

using AuditModel1_ConsoleApp;


// Create single instance of sample data from first line of dataset for model input
AuditModel1.ModelInput sampleData = new AuditModel1.ModelInput()
{
    Project = @"Project B",
    Business_Unit = @"IT",
    Expected_Duration__years_ = 1.5F,
    Actual_Duration__years_ = 0.5F,
    Budget_Amount = 200000F,
    Actual_Amount = 185000F,
    Team_Size = 12F,
};

// Make a single prediction on the sample data and print results
var predictionResult = AuditModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Result with predicted Result from sample data...\n\n");


Console.WriteLine($"Project: {@"Project B"}");
Console.WriteLine($"Business_Unit: {@"IT"}");
Console.WriteLine($"Expected_Duration__years_: {1.5F}");
Console.WriteLine($"Actual_Duration__years_: {0.5F}");
Console.WriteLine($"Budget_Amount: {200000F}");
Console.WriteLine($"Actual_Amount: {185000F}");
Console.WriteLine($"Team_Size: {12F}");
Console.WriteLine($"Result: {@"Not Successful"}");


Console.WriteLine($"\n\nPredicted Result: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

