// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AuditPredictor
{
    public partial class AuditModel1
    {
        /// <summary>
        /// model input class for AuditModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Project")]
            public string Project { get; set; }

            [ColumnName(@"Business Unit")]
            public string Business_Unit { get; set; }

            [ColumnName(@"Expected Duration (years)")]
            public float Expected_Duration__years_ { get; set; }

            [ColumnName(@"Actual Duration (years)")]
            public float Actual_Duration__years_ { get; set; }

            [ColumnName(@"Budget Amount")]
            public float Budget_Amount { get; set; }

            [ColumnName(@"Actual Amount")]
            public float Actual_Amount { get; set; }

            [ColumnName(@"Team Size")]
            public float Team_Size { get; set; }

            [ColumnName(@"Result")]
            public string Result { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for AuditModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Project")]
            public float[] Project { get; set; }

            [ColumnName(@"Business Unit")]
            public float[] Business_Unit { get; set; }

            [ColumnName(@"Expected Duration (years)")]
            public float Expected_Duration__years_ { get; set; }

            [ColumnName(@"Actual Duration (years)")]
            public float Actual_Duration__years_ { get; set; }

            [ColumnName(@"Budget Amount")]
            public float Budget_Amount { get; set; }

            [ColumnName(@"Actual Amount")]
            public float Actual_Amount { get; set; }

            [ColumnName(@"Team Size")]
            public float Team_Size { get; set; }

            [ColumnName(@"Result")]
            public uint Result { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AuditModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
